### PR TITLE
fix tests and add php8.0 support

### PR DESCRIPTION
**Pull request by saintdron**

### CODE REVIEW

**Comment by funivan** [comment]
We have github actions. Can you remove travis config?

**Comment by saintdron** [comment]
Of course. Done.

**Comment by funivan** [comment]
@saintdron can you add php 8 check to github actions?

**Comment by saintdron** [comment]
I didn't understand the question. Github actions already check PHP 8.0: 
https://github.com/xparse/ElementFinder/actions/runs/527309906
https://github.com/saintdron/ElementFinder/actions/runs/578067655

**Comment by funivan** [comment]
Ok, let me merge it and we will check how it is going.

**Pull request merged**
